#ifndef PROJECT_CONF_
#define PROJECT_CONF_

#define NETSTACK_CONF_MAC mac_dpm_driver
#define LOG_LEVEL_CONF_MAC_DPM_MAIN LOG_LEVEL_INFO
#define LOG_LEVEL_CONF_MAC_DPM_MINIMIZATION LOG_LEVEL_DBG
#define MAC_DPM_CONF_MINIMIZATION_SEQUENCE {0, -1, -3, -5, -7, -10, -15, -25}

#endif /* PROJECT_CONF_ */
