/*
 * UNDERLYING_MAC_DRIVER - sets the MAC driver which will be used (CSMA, TSCH, ...)
 * UNDERLYING_MAC_DRIVER_PATH - this is needed for importing the correct header
 * MAC_DPM_BEACON_INTERVAL_SECONDS - interval of the neighbor discovery beacon discovery beacon
 */
#ifndef MAC_DPM_CONF_
#define MAC_DPM_CONF_

#ifndef UNDERLYING_MAC_DRIVER_PATH
#define UNDERLYING_MAC_DRIVER_PATH "net/mac/csma/csma.h"
#endif /* UNDERLYING_MAC_DRIVER_PATH */

#include UNDERLYING_MAC_DRIVER_PATH

#ifndef UNDERLYING_MAC_DRIVER
#define UNDERLYING_MAC_DRIVER csma_driver /* The default MAC driver */
#endif /* UNDERLYING_MAC_DRIVER */

#ifdef MAC_DPM_CONF_BEACON_INTERVAL_SECONDS
#define MAC_DPM_BEACON_INTERVAL_SECONDS MAC_DPM_CONF_BEACON_INTERVAL_SECONDS
#else
#define MAC_DPM_BEACON_INTERVAL_SECONDS 60
#endif /* MAC_DPM_CONF_BEACON_INTERVAL_SECONDS */

#ifdef MAC_DPM_CONF_WAIT_FOR_ACK_PERIOD_SECONDS
#define MAC_DPM_WAIT_FOR_ACK_PERIOD_SECONDS MAC_DPM_CONF_WAIT_FOR_ACK_PERIOD_SECONDS
#else
#define MAC_DPM_WAIT_FOR_ACK_PERIOD_SECONDS 2
#endif /* MAC_DPM_CONF_WAIT_FOR_ACK_PERIOD_SECONDS */

#ifdef MAC_DPM_CONF_LOG_LEVEL_MAC_DPM
#define LOG_LEVEL_CONF_MAC_DPM_MAIN MAC_DPM_CONF_LOG_LEVEL_MAC_DPM
#define LOG_LEVEL_CONF_DPM_NBR MAC_DPM_CONF_LOG_LEVEL_MAC_DPM
#define LOG_LEVEL_CONF_DPM_OUTPUT MAC_DPM_CONF_LOG_LEVEL_MAC_DPM
#define LOG_LEVEL_CONF_DPM_DRIVER MAC_DPM_CONF_LOG_LEVEL_MAC_DPM
#define LOG_LEVEL_CONF_MAC_DPM_MINIMIZATION MAC_DPM_CONF_LOG_LEVEL_MAC_DPM
#endif /* MAC_DPM_CONF_LOG_LEVEL_MAC_DPM */

#ifdef LOG_LEVEL_CONF_MAC_DPM_MAIN
#define LOG_LEVEL_MAC_DPM_MAIN LOG_LEVEL_CONF_MAC_DPM_MAIN
#else
#define LOG_LEVEL_MAC_DPM_MAIN LOG_LEVEL_NONE
#endif /* LOG_LEVEL_CONF_MAC_DPM_MAIN */

#ifdef LOG_LEVEL_CONF_MAC_DPM_NBR
#define LOG_LEVEL_MAC_DPM_NBR LOG_LEVEL_CONF_MAC_DPM_NBR
#else
#define LOG_LEVEL_MAC_DPM_NBR LOG_LEVEL_NONE
#endif /* LOG_LEVEL_CONF_MAC_DPM_NBR */

#ifdef LOG_LEVEL_CONF_MAC_DPM_OUTPUT
#define LOG_LEVEL_MAC_DPM_OUTPUT LOG_LEVEL_CONF_MAC_DPM_OUTPUT
#else
#define LOG_LEVEL_MAC_DPM_OUTPUT LOG_LEVEL_NONE
#endif /* LOG_LEVEL_CONF_MAC_DPM_OUTPUT */

#ifdef LOG_LEVEL_CONF_MAC_DPM_DRIVER
#define LOG_LEVEL_MAC_DPM_DRIVER LOG_LEVEL_CONF_MAC_DPM_DRIVER
#else
#define LOG_LEVEL_MAC_DPM_DRIVER LOG_LEVEL_NONE
#endif /* LOG_LEVEL_CONF_MAC_DPM_DRIVER */

#ifdef LOG_LEVEL_CONF_MAC_DPM_MINIMIZATION
#define LOG_LEVEL_MAC_DPM_MINIMIZATION LOG_LEVEL_CONF_MAC_DPM_MINIMIZATION
#else
#define LOG_LEVEL_MAC_DPM_MINIMIZATION LOG_LEVEL_NONE
#endif /* LOG_LEVEL_CONF_MAC_DPM_MINIMIZATION */

#endif /* MAC_DPM_CONF_ */