#define BUILD_WITH_SIMPLE_ENERGEST 1
#define ENERGEST_CONF_ON 1
#define ENERGEST_CONF_ADDITIONS ENERGEST_TYPE_TX_0, ENERGEST_TYPE_TX_1, \
        ENERGEST_TYPE_TX_3, ENERGEST_TYPE_TX_5, ENERGEST_TYPE_TX_7, \
        ENERGEST_TYPE_TX_10, ENERGEST_TYPE_TX_15, ENERGEST_TYPE_TX_25
